import { useCallback, useEffect, useState } from 'react';
import { Database, Download, FileBox, Image as ImageIcon, Loader2, RotateCw } from 'lucide-react';
import { resourcesApi, type SessionResource } from '../../lib/api';
import { useStream } from '../../store/stream';

const REFRESH_MS = 5000;

function formatBytes(b: number): string {
  if (!Number.isFinite(b) || b <= 0) return '0 B';
  if (b < 1024) return `${b} B`;
  if (b < 1024 * 1024) return `${(b / 1024).toFixed(1)} KB`;
  return `${(b / (1024 * 1024)).toFixed(1)} MB`;
}

/** Short MIME label, e.g. `application/pdf` → `pdf`. */
function shortMime(mime: string): string {
  const base = mime.split(';')[0] ?? mime;
  const sub = base.split('/').pop() || mime;
  return sub.replace(/^x-/, '').replace(/^vnd\..*\./, '');
}

/**
 * **Data** tab: every persisted resource an agent acquired this session — images read/generated by
 * tools, and binary blobs fetched by `webfetch`. Images preview as thumbnails; blobs show as
 * downloadable file chips. Handles (`img_N` / `blob_N`) are what the agent references to analyse,
 * forward, or `write` them. Store-scoped to the active session; polled lightly for new arrivals.
 */
export function DataPanel() {
  const sessionId = useStream((s) => s.activeSessionId);
  const [resources, setResources] = useState<SessionResource[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const load = useCallback(async () => {
    if (!sessionId) return;
    try {
      setResources(await resourcesApi.list(sessionId));
      setError(null);
    } catch {
      setError('Failed to load resources.');
    }
  }, [sessionId]);

  useEffect(() => {
    if (!sessionId) {
      setResources([]);
      return;
    }
    setLoading(true);
    load().finally(() => setLoading(false));
    const t = setInterval(load, REFRESH_MS);
    return () => clearInterval(t);
  }, [sessionId, load]);

  if (!sessionId) {
    return <Centered>Select a session to see its resources.</Centered>;
  }

  if (loading && resources.length === 0) {
    return (
      <Centered>
        <Loader2 size={22} className="animate-spin text-slate-600" />
      </Centered>
    );
  }

  if (resources.length === 0) {
    return (
      <div className="flex h-full flex-col items-center justify-center gap-2 px-8 text-center text-slate-500">
        <Database size={30} className="text-slate-700" />
        <p className="text-sm font-medium text-slate-400">No resources yet</p>
        <p className="text-xs leading-relaxed">
          Images an agent reads and binary files it fetches (
          <span className="text-slate-300">webfetch</span> on a PDF, image, or archive) appear here as
          reusable <span className="font-mono text-slate-300">img_N</span> /{' '}
          <span className="font-mono text-slate-300">blob_N</span> handles.
        </p>
        {error && <p className="text-xs text-red-400/80">{error}</p>}
      </div>
    );
  }

  return (
    <div className="flex min-h-0 flex-1 flex-col">
      <div className="flex items-center gap-2 border-b border-white/[0.06] px-3 py-1.5">
        <Database size={13} className="text-slate-400" />
        <span className="text-xs font-medium text-slate-300">
          {resources.length} resource{resources.length > 1 ? 's' : ''}
        </span>
        <button
          onClick={load}
          title="Refresh"
          className="ml-auto rounded p-1 text-slate-500 hover:bg-white/[0.06] hover:text-slate-200"
        >
          <RotateCw size={13} />
        </button>
      </div>
      <div className="min-h-0 flex-1 space-y-2 overflow-y-auto p-3">
        {resources.map((r) => (
          <ResourceCard key={r.handle} sessionId={sessionId} resource={r} />
        ))}
      </div>
    </div>
  );
}

function ResourceCard({ sessionId, resource }: { sessionId: string; resource: SessionResource }) {
  const isImage = resource.kind === 'image';
  return (
    <div className="animate-fade-up flex gap-3 rounded-xl bg-black/25 p-2.5 backdrop-blur-sm ring-1 ring-white/[0.06]">
      {isImage ? (
        <ResourceThumb sessionId={sessionId} handle={resource.handle} />
      ) : (
        <div className="flex h-14 w-14 shrink-0 items-center justify-center rounded-lg bg-white/[0.04] text-slate-500">
          <FileBox size={22} />
        </div>
      )}
      <div className="flex min-w-0 flex-1 flex-col justify-center gap-0.5">
        <div className="flex items-center gap-1.5">
          {isImage ? (
            <ImageIcon size={12} className="shrink-0 text-accent" />
          ) : (
            <FileBox size={12} className="shrink-0 text-amber-400" />
          )}
          <span className="truncate font-mono text-xs text-slate-200">{resource.handle}</span>
          <span className="ml-auto shrink-0 text-[10px] text-slate-500">{formatBytes(resource.size)}</span>
        </div>
        <div className="truncate text-[11px] text-slate-500" title={resource.filename || resource.mime}>
          {resource.filename ? `${resource.filename} · ` : ''}
          <span className="font-mono">{shortMime(resource.mime)}</span>
        </div>
        <button
          onClick={() => resourcesApi.download(sessionId, resource.handle, resource.filename)}
          className="mt-0.5 flex w-fit items-center gap-1 rounded-md bg-white/[0.05] px-2 py-0.5 text-[10px] text-slate-300 hover:bg-white/[0.09] hover:text-slate-100"
        >
          <Download size={11} /> Download
        </button>
      </div>
    </div>
  );
}

/** Fetches an image resource's bytes into an object URL for the thumbnail (revoked on unmount). */
function ResourceThumb({ sessionId, handle }: { sessionId: string; handle: string }) {
  const [url, setUrl] = useState<string | null>(null);

  useEffect(() => {
    let revoked = false;
    let objectUrl: string | null = null;
    resourcesApi
      .objectUrl(sessionId, handle)
      .then((u) => {
        objectUrl = u;
        if (revoked) URL.revokeObjectURL(u);
        else setUrl(u);
      })
      .catch(() => {});
    return () => {
      revoked = true;
      if (objectUrl) URL.revokeObjectURL(objectUrl);
    };
  }, [sessionId, handle]);

  return (
    <a
      href={url ?? undefined}
      target="_blank"
      rel="noreferrer"
      className="flex h-14 w-14 shrink-0 items-center justify-center overflow-hidden rounded-lg bg-white/[0.04]"
    >
      {url ? (
        <img src={url} alt={handle} className="h-full w-full object-cover" />
      ) : (
        <Loader2 size={16} className="animate-spin text-slate-600" />
      )}
    </a>
  );
}

function Centered({ children }: { children: React.ReactNode }) {
  return (
    <div className="flex h-full flex-col items-center justify-center px-6 text-center text-sm text-slate-500">
      {children}
    </div>
  );
}
